# -*- coding: utf-8 -*-
"""Normalization

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16zbEheBahrrO6RD5Tc0g-NhRFsizWfRZ
"""

import numpy as np
from scipy import stats
import pandas as pd
import cv2 as cv 
from google.colab.patches import cv2_imshow # for image display
from skimage import io
import matplotlib.pylab as plt

url = "https://thumbs.dreamstime.com/b/christmas-lights-raised-night-horizon-city-houses-around-lampposts-varied-lighting-addition-to-some-palm-112537572.jpg"
img = io.imread(url)  
cv2_imshow(img)

gray_img = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
cv2_imshow(gray_img)

#cv2.imwrite("Grayscale Image.png",img)  #To write the result  

normalized_img = stats.zscore(gray_img)
cv2_imshow(normalized_img)
normalized_img *= 255
cv2_imshow(normalized_img)

#cv2.imwrite("Normalized Image.png",image)  #To write the result